name: ci
on:
    push:
        branches:
        - main 
        - feature/*
env:
  MONGO_URI: ${{ vars.MONGO_URL }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}

jobs:
    npm_setup:
        runs-on: 'ubuntu-latest'
        steps:
        -  name: checkout
           uses:  actions/checkout@v4
        -  name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: 18

        - name: install dependancy
          run: npm install
        - name: unit testing
          run: npm test

        - name: upload  unit test report
          uses: actions/up;oad-artifacts@v3
          with: 
            name: unitTest Result
            path: test-results.xml
          