name: ci
on:
    push:
        branches:
        - main 
        - feature/*
env:
  MONGO_URI: ${{ vars.MONGO_URL }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}


jobs:
    npm_setup:
        runs-on: ${{ matrix.operating_system }}
        strategy:
            matrix:
               nodejs_version: [18,19,20]
               operating_system: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]

        steps:
        -  name: checkout
           uses:  actions/checkout@v4
        -  name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: ${{ matrix.nodejs_version}}

        - name: install dependancy
          run: npm install
        - name: unit testing
          run: npm test

        - name: change report name
          run: mv test-results.xml test-results-${{github.run_id}}.xml

        - name: upload  unit test report
          uses: actions/upload-artifact@v4
          with: 
            name: unitTestReport-${{github.run_id}}
            path: test-results-${{github.run_id}}.xml
          