name: ci
on:
    push:
        branches:
        - main 
        - feature/*
env:
  MONGO_URI: ${{ vars.MONGO_URL }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}


jobs:
    run_test:
        runs-on: ${{ matrix.operating_system }}
        strategy:
            matrix:
               nodejs_version: [18,19]
               operating_system: [ ubuntu-24.04, ubuntu-latest]

        steps:
        -  name: checkout
           uses:  actions/checkout@v4
        -  name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: ${{ matrix.nodejs_version}}

        - name: install dependancy
          run: npm install
        - name: unit testing
          run: npm test

        - name: change report name
          run: mv test-results.xml test-results-${{matrix.operating_system}}-${{matrix.nodejs_version}}.xml

        - name: upload  unit test report
          uses: actions/upload-artifact@v4
          with: 
            name: unitTestReport-${{matrix.operating_system}}-${{matrix.nodejs_version}}
            path: test-results-${{matrix.operating_system}}-${{matrix.nodejs_version}}.xml

    run_code_coverage:
        runs-on: 'ubuntu-latest'
        steps:
        -  name: checkout
           uses:  actions/checkout@v4
        -  name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: 18

        - name: install dependancy
          run: npm install
        - name: unit testing
          run: npm run coverage
          
         # continue-on-error: true  # it will excute and test is marked as pass

        - name: upload code coverage report
          #if: failure() # if stattement step and job will be failed even all step executed
          if : always()
          uses: actions/upload-artifact@v4
          with: 
            name: code-coverage-${{github.sha}}
            path: coverage         
            retention-days: 1